repos:
- repo: local
  hooks:
    - id: linter
      name: Check code format
      entry: make lint_all
      language: system
- repo: local
  hooks:
  - id: tests
    name: Execute unit tests
    entry: make test_all
    language: system
    stages: [push]
