kafka:
  broker: localhost:29092
  topics:
    raw_data:
      partitions: 5
      replication: 1
      recreate: false
  producer:
    configuration:
      queue.buffering.max.ms: 2000 # flush buffer every 2 seconds
      #queue.buffering.max.messages: 10 # flush every 10 messages
generation:
  late_data_percentage: 10
dataset:
  all_users: 1000
  real_time_delta_seconds: -900
  session_duration_seconds:
    min: 10
    max: 300
  composition_percentage:
    incomplete: 2
    inconsistent: 2
    fully_valid: 96
  versions_percentage:
    v1: 20
    v2: 20
  users_no_data_consent_percentage: 2